# Alpha Finder 配置文件
import os

try:
    import winreg
except ImportError:  # pragma: no cover - Windows only helper
    winreg = None


def _getenv(name: str, default: str = "") -> str:
    value = os.getenv(name)
    if value not in (None, ""):
        return str(value).replace("\ufeff", "").strip()

    if winreg is not None:
        try:
            with winreg.OpenKey(winreg.HKEY_CURRENT_USER, r"Environment") as key:
                reg_value, _ = winreg.QueryValueEx(key, name)
                if reg_value not in (None, ""):
                    return str(reg_value).replace("\ufeff", "").strip()
        except OSError:
            pass

    return default


def _getenv_bool(name: str, default: str = "false") -> bool:
    return _getenv(name, default).strip().lower() == "true"


ALPHA_FINDER_LOG_LEVEL = _getenv("ALPHA_FINDER_LOG_LEVEL", _getenv("LOG_LEVEL", "INFO")).upper()

# ============ 市場和指數配置 ============
# 🎯 根據投資策略選擇要監控的市場/指數
# 💡 建議: 使用單個指數達到最佳效果，避免過度限制搜尋結果
# ⚠️  同時使用多個市場和指數會導致篩選條件過嚴格，返回 0 結果

SELECTED_EXCHANGES = []  # 留空表示使用所有市場

SELECTED_INDICES = [
    'idx_sp500',           # ✅ S&P 500 - 美股大盤 500 強
    'idx_ndx',             # ✅ Nasdaq 100 - 科技股為主
    'idx_russell2000',     # ✅ Russell 2000 - 小型股
    # 'idx_philly_smh',    # Philadelphia Semiconductor - 半導體
    # 'idx_dji',           # Dow Jones - 道瓊指數
]

# ============ Finviz 設定 ============
# 最多爬取幾頁（每頁 20 筆）
# 提高至 5 頁以覆蓋龍頭股（NVDA、TSLA 等大盤股容易排名靠後）
MAX_PAGES = 5

# ============ Yahoo Finance 設定 ============
# 最多處理幾檔股票（避免 API 限制）
# 提高至 120 以涵蓋全市場強勢股
MAX_STOCKS_TO_PROCESS = 120

# API 請求延遲（秒）
API_DELAY = 0.5

# ============ 篩選條件 ============
# 起飛清單
LAUNCH_MIN_GAIN = 3.0          # 最低漲幅 %
LAUNCH_MIN_REL_VOL = 1.8       # 最低相對量能倍數
LAUNCH_MIN_PRICE = 5.0         # 最低股價
LAUNCH_MIN_MCAP = 100_000_000  # 最低市值（美元）

# 財報預熱
EARNINGS_DAYS_AHEAD = 7              # 未來幾天內的財報
EARNINGS_MIN_MCAP = 1_000_000_000    # 最低市值（美元）
EARNINGS_MIN_VOLUME = 500_000        # 最低平均成交量（Finnhub 補強用）
MAX_EARNINGS_MERGE = 80              # Finnhub 財報補抓最大數量（防止爆量）
EARNINGS_RESERVED_SLOTS = 40         # 財報股保留名額（不受信號排名截斷）

# 財報拆分（新）
EARNINGS_LOOKAHEAD_DAYS = int(os.getenv("EARNINGS_LOOKAHEAD_DAYS", "14"))
EARNINGS_LOOKBACK_DAYS = int(os.getenv("EARNINGS_LOOKBACK_DAYS", "5"))
EARNINGS_SNIPER_DAYS = int(os.getenv("EARNINGS_SNIPER_DAYS", "3"))

# 財報市值分級門檻（新）
EARNINGS_TIER1_MCAP_MIN = int(os.getenv("EARNINGS_TIER1_MCAP_MIN", "2000000000"))
EARNINGS_TIER2_MCAP_MIN = int(os.getenv("EARNINGS_TIER2_MCAP_MIN", "300000000"))

# 預測情報
ANALYST_MIN_UPSIDE = 30.0      # 最低上漲空間 %
ANALYST_MIN_COUNT = 3          # 最低分析師數量

# ============ 評級設定 ============
# A 級條件：量能倍數門檻
RATING_A_REL_VOL = 2.5
# A 級條件：上漲空間門檻
RATING_A_UPSIDE = 50.0

# ============ 輸出設定 ============
# 每個清單輸出幾檔股票
TOP_N_STOCKS = 3

# ============ 大盤環境濾網（MVP，可關閉） ============
# 啟用後：若 SPY 跌破 MA20，將自動提高部分選股門檻
MARKET_FILTER_ENABLED = os.getenv("MARKET_FILTER_ENABLED", "false").lower() == "true"
MARKET_FILTER_SYMBOL = os.getenv("MARKET_FILTER_SYMBOL", "SPY").upper()
MARKET_FILTER_MA_WINDOW = int(os.getenv("MARKET_FILTER_MA_WINDOW", "20"))
MARKET_FILTER_LOOKBACK_DAYS = int(os.getenv("MARKET_FILTER_LOOKBACK_DAYS", "60"))

# Bear 模式（SPY < MA20）門檻
MARKET_FILTER_BEAR_LAUNCH_MIN_GAIN = float(os.getenv("MARKET_FILTER_BEAR_LAUNCH_MIN_GAIN", "4.5"))
MARKET_FILTER_BEAR_LAUNCH_MIN_REL_VOL = float(os.getenv("MARKET_FILTER_BEAR_LAUNCH_MIN_REL_VOL", "2.5"))
MARKET_FILTER_BEAR_EARNINGS_MIN_MCAP = int(os.getenv("MARKET_FILTER_BEAR_EARNINGS_MIN_MCAP", "2000000000"))
MARKET_FILTER_BEAR_ANALYST_MIN_UPSIDE = float(os.getenv("MARKET_FILTER_BEAR_ANALYST_MIN_UPSIDE", "40.0"))

# ============ Google Sheets 設定（選用）============
GSHEET_ENABLED = True
GSHEET_NAME = "Alpha_Sniper_Daily_Report"
GSHEET_CREDENTIALS_FILE = "credentials.json"
GSHEET_UPLOAD_DAILY_REPORT = True
GSHEET_UPLOAD_FULL_DATA = False

# ============ 本地每日輸出（推薦） ============
# 每日刷新的資料優先存 repo，本地給 AI 讀取更穩定
LOCAL_OUTPUT_ENABLED = True
LOCAL_OUTPUT_DIR = "repo_outputs/daily_refresh"
LOCAL_OUTPUT_KEEP_DAYS = 14

# ============ AI 五檔快捷輸出（推薦） ============
# 固定輸出給 AI 的 5 檔入口，避免在大量 CSV 中尋找
AI_READY_OUTPUT_ENABLED = True
AI_READY_OUTPUT_DIR = "repo_outputs/ai_ready"
AI_READY_KEEP_DAYS = 14

# ============ 每週制度化評估輸出（零人工） ============
WEEKLY_REPORT_ENABLED = os.getenv("WEEKLY_REPORT_ENABLED", "true").lower() == "true"
WEEKLY_REPORT_OUTPUT_DIR = os.getenv("WEEKLY_REPORT_OUTPUT_DIR", "repo_outputs/backtest/weekly_reports")
WEEKLY_REPORT_LOOKBACK_DAYS = int(os.getenv("WEEKLY_REPORT_LOOKBACK_DAYS", "7"))
WEEKLY_REPORT_HOLD_DAYS = int(os.getenv("WEEKLY_REPORT_HOLD_DAYS", "1"))
WEEKLY_REPORT_MAX_RANK = int(os.getenv("WEEKLY_REPORT_MAX_RANK", "10"))
WEEKLY_REPORT_MAX_SYMBOLS = int(os.getenv("WEEKLY_REPORT_MAX_SYMBOLS", "80"))

# ============ API金鑰設定 ============
# Finnhub 免費 API (60 call/min) - 財報日期 + 分析師目標價
# 註冊: https://finnhub.io/register
# 使用環境變數：FINNHUB_API_KEY
FINNHUB_API_KEY = _getenv("FINNHUB_API_KEY", "")

# ============ 彩票股設定 (Track F) ============
LOTTERY_MIN_GAIN = 10.0        # 單日漲幅 >10%
LOTTERY_MIN_REL_VOL = 3.0      # 量能倍數 >3
LOTTERY_MAX_MCAP = 50_000_000_000  # 市值 <$50B

# ============ 妖股雷達設定 (Monster Radar) ============
MONSTER_RADAR_ENABLED = os.getenv("MONSTER_RADAR_ENABLED", "true").lower() == "true"
MONSTER_TOP_K = int(os.getenv("MONSTER_TOP_K", "12"))
MONSTER_MIN_GAIN = float(os.getenv("MONSTER_MIN_GAIN", "4.0"))
MONSTER_MIN_REL_VOL = float(os.getenv("MONSTER_MIN_REL_VOL", "1.8"))
MONSTER_MIN_PRICE = float(os.getenv("MONSTER_MIN_PRICE", "1.0"))
MONSTER_MAX_MCAP = int(os.getenv("MONSTER_MAX_MCAP", "30000000000"))
MONSTER_SCORE_300 = float(os.getenv("MONSTER_SCORE_300", "28"))
MONSTER_SCORE_500 = float(os.getenv("MONSTER_SCORE_500", "34"))
MONSTER_SCORE_1000 = float(os.getenv("MONSTER_SCORE_1000", "42"))
MONSTER_USE_SIGNAL_BOOST = os.getenv("MONSTER_USE_SIGNAL_BOOST", "true").lower() == "true"

# ============ AI Trading 排名引擎設定 ============
AI_RANK_TOP_K = int(os.getenv("AI_RANK_TOP_K", "80"))
AI_RANK_BASE_WEIGHT = float(os.getenv("AI_RANK_BASE_WEIGHT", "0.42"))
AI_RANK_FEATURE_WEIGHT = float(os.getenv("AI_RANK_FEATURE_WEIGHT", "0.28"))
AI_RANK_RADAR_WEIGHT = float(os.getenv("AI_RANK_RADAR_WEIGHT", "0.20"))
AI_RANK_EVENT_WEIGHT = float(os.getenv("AI_RANK_EVENT_WEIGHT", "0.10"))
AI_RANK_MONSTER_BONUS_WEIGHT = float(os.getenv("AI_RANK_MONSTER_BONUS_WEIGHT", "0.08"))
AI_RANK_FOCUS_BONUS = float(os.getenv("AI_RANK_FOCUS_BONUS", "1.5"))
AI_RANK_FUSION_BONUS = float(os.getenv("AI_RANK_FUSION_BONUS", "1.0"))

# Regime 判斷（強勢股佔比）
AI_RANK_REGIME_BULL_MIN_BREADTH = float(os.getenv("AI_RANK_REGIME_BULL_MIN_BREADTH", "0.22"))
AI_RANK_REGIME_BEAR_MAX_BREADTH = float(os.getenv("AI_RANK_REGIME_BEAR_MAX_BREADTH", "0.10"))

# Regime 權重倍率
AI_RANK_BULL_BASE_MULT = float(os.getenv("AI_RANK_BULL_BASE_MULT", "1.15"))
AI_RANK_BULL_FEATURE_MULT = float(os.getenv("AI_RANK_BULL_FEATURE_MULT", "1.10"))
AI_RANK_BULL_RADAR_MULT = float(os.getenv("AI_RANK_BULL_RADAR_MULT", "0.90"))
AI_RANK_BULL_EVENT_MULT = float(os.getenv("AI_RANK_BULL_EVENT_MULT", "0.85"))

AI_RANK_BEAR_BASE_MULT = float(os.getenv("AI_RANK_BEAR_BASE_MULT", "0.80"))
AI_RANK_BEAR_FEATURE_MULT = float(os.getenv("AI_RANK_BEAR_FEATURE_MULT", "0.90"))
AI_RANK_BEAR_RADAR_MULT = float(os.getenv("AI_RANK_BEAR_RADAR_MULT", "1.15"))
AI_RANK_BEAR_EVENT_MULT = float(os.getenv("AI_RANK_BEAR_EVENT_MULT", "1.25"))

# Tier 門檻
AI_RANK_TIER_A_MIN = float(os.getenv("AI_RANK_TIER_A_MIN", "42.0"))
AI_RANK_TIER_B_MIN = float(os.getenv("AI_RANK_TIER_B_MIN", "30.0"))

# ============ Feature Engine 設定 ============
FEATURE_GRADE_A_SCORE = float(_getenv("FEATURE_GRADE_A_SCORE", "8.0"))
FEATURE_GRADE_B_SCORE = float(_getenv("FEATURE_GRADE_B_SCORE", "5.5"))
FEATURE_GRADE_C_SCORE = float(_getenv("FEATURE_GRADE_C_SCORE", "3.0"))
FEATURE_GRADE_D_SCORE = float(_getenv("FEATURE_GRADE_D_SCORE", "1.0"))
FEATURE_TREND_PROB_WEIGHT = float(_getenv("FEATURE_TREND_PROB_WEIGHT", "0.08"))
FEATURE_VOLATILITY_DAILY_WEIGHT = float(_getenv("FEATURE_VOLATILITY_DAILY_WEIGHT", "0.9"))
FEATURE_VOLATILITY_XQ3D_WEIGHT = float(_getenv("FEATURE_VOLATILITY_XQ3D_WEIGHT", "0.45"))
FEATURE_VOLATILITY_XQ5D_WEIGHT = float(_getenv("FEATURE_VOLATILITY_XQ5D_WEIGHT", "0.3"))
FEATURE_FLOAT_BASE_WEIGHT = float(_getenv("FEATURE_FLOAT_BASE_WEIGHT", "18.0"))
FEATURE_FLOAT_LIQUIDITY_WEIGHT = float(_getenv("FEATURE_FLOAT_LIQUIDITY_WEIGHT", "0.28"))
FEATURE_SQUEEZE_REL_VOL_WEIGHT = float(_getenv("FEATURE_SQUEEZE_REL_VOL_WEIGHT", "2.6"))
FEATURE_SQUEEZE_MOMENTUM_WEIGHT = float(_getenv("FEATURE_SQUEEZE_MOMENTUM_WEIGHT", "0.45"))
FEATURE_SQUEEZE_SETUP_WEIGHT = float(_getenv("FEATURE_SQUEEZE_SETUP_WEIGHT", "0.35"))
FEATURE_EARNINGS_NEAR_SCORE = float(_getenv("FEATURE_EARNINGS_NEAR_SCORE", "10.0"))
FEATURE_EARNINGS_MID_SCORE = float(_getenv("FEATURE_EARNINGS_MID_SCORE", "6.0"))
FEATURE_EARNINGS_FAR_SCORE = float(_getenv("FEATURE_EARNINGS_FAR_SCORE", "3.0"))
FEATURE_EARNINGS_POST_SCORE = float(_getenv("FEATURE_EARNINGS_POST_SCORE", "5.0"))
FEATURE_ANALYST_UPSIDE_WEIGHT = float(_getenv("FEATURE_ANALYST_UPSIDE_WEIGHT", "0.2"))
FEATURE_ANALYST_COUNT_WEIGHT = float(_getenv("FEATURE_ANALYST_COUNT_WEIGHT", "1.1"))
FEATURE_ANALYST_CORE_WEIGHT = float(_getenv("FEATURE_ANALYST_CORE_WEIGHT", "0.12"))
FEATURE_NEWS_ATTENTION_WEIGHT = float(_getenv("FEATURE_NEWS_ATTENTION_WEIGHT", "4.2"))
FEATURE_NEWS_REL_VOL_WEIGHT = float(_getenv("FEATURE_NEWS_REL_VOL_WEIGHT", "0.8"))
FEATURE_NEWS_DAILY_WEIGHT = float(_getenv("FEATURE_NEWS_DAILY_WEIGHT", "0.18"))
FEATURE_ALPHA_TREND_WEIGHT = float(_getenv("FEATURE_ALPHA_TREND_WEIGHT", "0.9"))
FEATURE_ALPHA_ACCEL_1D3D_WEIGHT = float(_getenv("FEATURE_ALPHA_ACCEL_1D3D_WEIGHT", "0.7"))
FEATURE_ALPHA_ACCEL_3D5D_WEIGHT = float(_getenv("FEATURE_ALPHA_ACCEL_3D5D_WEIGHT", "0.5"))
FEATURE_ALPHA_SQUEEZE_WEIGHT = float(_getenv("FEATURE_ALPHA_SQUEEZE_WEIGHT", "0.55"))
FEATURE_ALPHA_MONSTER_WEIGHT = float(_getenv("FEATURE_ALPHA_MONSTER_WEIGHT", "0.12"))
FEATURE_ALPHA_FLOAT_WEIGHT = float(_getenv("FEATURE_ALPHA_FLOAT_WEIGHT", "0.35"))
FEATURE_ALPHA_ANALYST_WEIGHT = float(_getenv("FEATURE_ALPHA_ANALYST_WEIGHT", "0.5"))
FEATURE_ALPHA_EARNINGS_WEIGHT = float(_getenv("FEATURE_ALPHA_EARNINGS_WEIGHT", "0.8"))
FEATURE_ALPHA_NEWS_WEIGHT = float(_getenv("FEATURE_ALPHA_NEWS_WEIGHT", "0.45"))
FEATURE_ALPHA_VOLATILITY_PENALTY = float(_getenv("FEATURE_ALPHA_VOLATILITY_PENALTY", "0.3"))
FEATURE_PRIORITY_A_MIN = float(_getenv("FEATURE_PRIORITY_A_MIN", "40.0"))
FEATURE_PRIORITY_B_MIN = float(_getenv("FEATURE_PRIORITY_B_MIN", "27.0"))
FEATURE_HIT_MIN = float(_getenv("FEATURE_HIT_MIN", "27.0"))
FEATURE_HIT_TREND_MIN = float(_getenv("FEATURE_HIT_TREND_MIN", "10.0"))
FEATURE_HIT_SQUEEZE_MIN = float(_getenv("FEATURE_HIT_SQUEEZE_MIN", "18.0"))

# ============ Multi Radar 設定 ============
RADAR_SECTOR_STRONG_DAILY_MIN = float(_getenv("RADAR_SECTOR_STRONG_DAILY_MIN", "3.0"))
RADAR_SECTOR_STRONG_REL_VOL_MIN = float(_getenv("RADAR_SECTOR_STRONG_REL_VOL_MIN", "1.8"))
RADAR_SECTOR_MEDIAN_WEIGHT = float(_getenv("RADAR_SECTOR_MEDIAN_WEIGHT", "1.0"))
RADAR_SECTOR_REL_VOL_WEIGHT = float(_getenv("RADAR_SECTOR_REL_VOL_WEIGHT", "2.2"))
RADAR_SECTOR_STRONG_RATIO_WEIGHT = float(_getenv("RADAR_SECTOR_STRONG_RATIO_WEIGHT", "9.0"))
RADAR_SECTOR_HIT_MIN = float(_getenv("RADAR_SECTOR_HIT_MIN", "8.5"))
RADAR_SECTOR_HIT_DAILY_MIN = float(_getenv("RADAR_SECTOR_HIT_DAILY_MIN", "2.0"))
RADAR_SECTOR_HIT_REL_VOL_MIN = float(_getenv("RADAR_SECTOR_HIT_REL_VOL_MIN", "1.5"))
RADAR_POST_EARNINGS_WINDOW_START = int(_getenv("RADAR_POST_EARNINGS_WINDOW_START", "-5"))
RADAR_POST_EARNINGS_WINDOW_END = int(_getenv("RADAR_POST_EARNINGS_WINDOW_END", "-1"))
RADAR_POST_EARNINGS_DAY_WEIGHT = float(_getenv("RADAR_POST_EARNINGS_DAY_WEIGHT", "4.0"))
RADAR_POST_EARNINGS_DAILY_WEIGHT = float(_getenv("RADAR_POST_EARNINGS_DAILY_WEIGHT", "1.1"))
RADAR_POST_EARNINGS_REL_VOL_WEIGHT = float(_getenv("RADAR_POST_EARNINGS_REL_VOL_WEIGHT", "3.4"))
RADAR_POST_EARNINGS_CORE_WEIGHT = float(_getenv("RADAR_POST_EARNINGS_CORE_WEIGHT", "0.18"))
RADAR_POST_EARNINGS_SCORE_MIN = float(_getenv("RADAR_POST_EARNINGS_SCORE_MIN", "16.0"))
RADAR_POST_EARNINGS_DAILY_MIN = float(_getenv("RADAR_POST_EARNINGS_DAILY_MIN", "0.5"))
RADAR_POST_EARNINGS_REL_VOL_MIN = float(_getenv("RADAR_POST_EARNINGS_REL_VOL_MIN", "1.2"))
RADAR_SQUEEZE_TV_BONUS = float(_getenv("RADAR_SQUEEZE_TV_BONUS", "12.0"))
RADAR_SQUEEZE_REL_VOL_WEIGHT = float(_getenv("RADAR_SQUEEZE_REL_VOL_WEIGHT", "2.8"))
RADAR_SQUEEZE_DAILY_WEIGHT = float(_getenv("RADAR_SQUEEZE_DAILY_WEIGHT", "0.7"))
RADAR_SQUEEZE_MOMENTUM_WEIGHT = float(_getenv("RADAR_SQUEEZE_MOMENTUM_WEIGHT", "0.35"))
RADAR_SQUEEZE_MONSTER_WEIGHT = float(_getenv("RADAR_SQUEEZE_MONSTER_WEIGHT", "0.08"))
RADAR_SQUEEZE_PENALTY_GAIN = float(_getenv("RADAR_SQUEEZE_PENALTY_GAIN", "15.0"))
RADAR_SQUEEZE_PENALTY_REL_VOL = float(_getenv("RADAR_SQUEEZE_PENALTY_REL_VOL", "1.5"))
RADAR_SQUEEZE_PENALTY_VALUE = float(_getenv("RADAR_SQUEEZE_PENALTY_VALUE", "7.0"))
RADAR_SQUEEZE_ALT_REL_VOL_MIN = float(_getenv("RADAR_SQUEEZE_ALT_REL_VOL_MIN", "2.0"))
RADAR_SQUEEZE_SCORE_MIN = float(_getenv("RADAR_SQUEEZE_SCORE_MIN", "15.0"))
RADAR_MULTI_SECTOR_WEIGHT = float(_getenv("RADAR_MULTI_SECTOR_WEIGHT", "0.34"))
RADAR_MULTI_POST_WEIGHT = float(_getenv("RADAR_MULTI_POST_WEIGHT", "0.31"))
RADAR_MULTI_SQUEEZE_WEIGHT = float(_getenv("RADAR_MULTI_SQUEEZE_WEIGHT", "0.35"))
RADAR_PRIORITY_A_MIN = float(_getenv("RADAR_PRIORITY_A_MIN", "22.0"))
RADAR_PRIORITY_B_MIN = float(_getenv("RADAR_PRIORITY_B_MIN", "16.0"))

# ============ Event Detector 設定 ============
EVENT_VOL_BREAKOUT_DAILY_MIN = float(_getenv("EVENT_VOL_BREAKOUT_DAILY_MIN", "8.0"))
EVENT_VOL_BREAKOUT_REL_VOL_MIN = float(_getenv("EVENT_VOL_BREAKOUT_REL_VOL_MIN", "2.5"))
EVENT_VOL_BREAKOUT_DAILY_WEIGHT = float(_getenv("EVENT_VOL_BREAKOUT_DAILY_WEIGHT", "1.8"))
EVENT_VOL_BREAKOUT_REL_VOL_WEIGHT = float(_getenv("EVENT_VOL_BREAKOUT_REL_VOL_WEIGHT", "8.0"))
EVENT_VOL_BREAKOUT_MONSTER_WEIGHT = float(_getenv("EVENT_VOL_BREAKOUT_MONSTER_WEIGHT", "0.3"))
EVENT_EARNINGS_SNIPER_MAX_DAYS = int(_getenv("EVENT_EARNINGS_SNIPER_MAX_DAYS", "3"))
EVENT_EARNINGS_SNIPER_DAY_WEIGHT = float(_getenv("EVENT_EARNINGS_SNIPER_DAY_WEIGHT", "7.0"))
EVENT_EARNINGS_SNIPER_REL_VOL_WEIGHT = float(_getenv("EVENT_EARNINGS_SNIPER_REL_VOL_WEIGHT", "4.0"))
EVENT_EARNINGS_SNIPER_CORE_WEIGHT = float(_getenv("EVENT_EARNINGS_SNIPER_CORE_WEIGHT", "0.5"))
EVENT_POST_EARNINGS_MIN_DAYS = int(_getenv("EVENT_POST_EARNINGS_MIN_DAYS", "-2"))
EVENT_POST_EARNINGS_MAX_DAYS = int(_getenv("EVENT_POST_EARNINGS_MAX_DAYS", "0"))
EVENT_POST_EARNINGS_DAILY_MIN = float(_getenv("EVENT_POST_EARNINGS_DAILY_MIN", "2.0"))
EVENT_POST_EARNINGS_DAILY_WEIGHT = float(_getenv("EVENT_POST_EARNINGS_DAILY_WEIGHT", "1.2"))
EVENT_POST_EARNINGS_REL_VOL_WEIGHT = float(_getenv("EVENT_POST_EARNINGS_REL_VOL_WEIGHT", "5.0"))
EVENT_POST_EARNINGS_CORE_WEIGHT = float(_getenv("EVENT_POST_EARNINGS_CORE_WEIGHT", "0.25"))
EVENT_MONSTER_MIN_SCORE = float(_getenv("EVENT_MONSTER_MIN_SCORE", "34.0"))
EVENT_MONSTER_MIN_PROB = float(_getenv("EVENT_MONSTER_MIN_PROB", "55.0"))
EVENT_MONSTER_PROB_WEIGHT = float(_getenv("EVENT_MONSTER_PROB_WEIGHT", "0.4"))
EVENT_MONSTER_REL_VOL_WEIGHT = float(_getenv("EVENT_MONSTER_REL_VOL_WEIGHT", "2.0"))
EVENT_FOCUS_MONSTER_MIN_SCORE = float(_getenv("EVENT_FOCUS_MONSTER_MIN_SCORE", "25.0"))
EVENT_FOCUS_MONSTER_WEIGHT = float(_getenv("EVENT_FOCUS_MONSTER_WEIGHT", "0.8"))
EVENT_FOCUS_REL_VOL_WEIGHT = float(_getenv("EVENT_FOCUS_REL_VOL_WEIGHT", "3.0"))
EVENT_FOCUS_CORE_WEIGHT = float(_getenv("EVENT_FOCUS_CORE_WEIGHT", "0.2"))

# ============ AI Trading 決策風險層設定 ============
AI_DECISION_TOP_K = int(os.getenv("AI_DECISION_TOP_K", "80"))
AI_DECISION_KEEP_MIN_SCORE = float(os.getenv("AI_DECISION_KEEP_MIN_SCORE", "42.0"))
AI_DECISION_WATCH_MIN_SCORE = float(os.getenv("AI_DECISION_WATCH_MIN_SCORE", "30.0"))
AI_DECISION_MAX_KEEP_RISK_SCORE = float(os.getenv("AI_DECISION_MAX_KEEP_RISK_SCORE", "3.2"))

AI_DECISION_ENTRY_MIN_GAIN = float(os.getenv("AI_DECISION_ENTRY_MIN_GAIN", "2.0"))
AI_DECISION_ENTRY_MAX_GAIN = float(os.getenv("AI_DECISION_ENTRY_MAX_GAIN", "8.0"))
AI_DECISION_STRONG_VOL = float(os.getenv("AI_DECISION_STRONG_VOL", "1.8"))
AI_DECISION_LOW_VOL = float(os.getenv("AI_DECISION_LOW_VOL", "1.3"))
AI_DECISION_OVERHEAT_GAIN = float(os.getenv("AI_DECISION_OVERHEAT_GAIN", "12.0"))

# ============ AI Catalyst Detector（Tavily + Gemini Flash）===========
AI_RESEARCH_MODE = _getenv("AI_RESEARCH_MODE", "web").lower()  # web | api
CATALYST_DETECTOR_ENABLED = _getenv_bool("CATALYST_DETECTOR_ENABLED", "false")
CATALYST_TOP_K = int(os.getenv("CATALYST_TOP_K", "12"))
CATALYST_TAVILY_MAX_RESULTS = int(os.getenv("CATALYST_TAVILY_MAX_RESULTS", "4"))
CATALYST_HTTP_TIMEOUT_SEC = float(os.getenv("CATALYST_HTTP_TIMEOUT_SEC", "15.0"))

TAVILY_API_KEY = _getenv("TAVILY_API_KEY", _getenv("TAVILY_API", ""))
GEMINI_API_KEY = _getenv("GEMINI_API_KEY", _getenv("GEMINI_API", ""))
GEMINI_MODEL = _getenv("GEMINI_MODEL", "gemini-2.5-flash")
RECAP_GEMINI_ENABLED = _getenv_bool("RECAP_GEMINI_ENABLED", "true")
RECAP_GEMINI_TIMEOUT_SEC = float(_getenv("RECAP_GEMINI_TIMEOUT_SEC", "20.0"))
RECAP_TAVILY_ENABLED = _getenv_bool("RECAP_TAVILY_ENABLED", "true")
RECAP_TAVILY_MAX_RESULTS = int(_getenv("RECAP_TAVILY_MAX_RESULTS", "3"))
RECAP_CONFLICT_NEWS_MAX_TICKERS = int(_getenv("RECAP_CONFLICT_NEWS_MAX_TICKERS", "2"))
RECAP_EXECUTION_LOOKBACK_LIMIT = int(_getenv("RECAP_EXECUTION_LOOKBACK_LIMIT", "240"))
RECAP_BEDTIME_UTC_START_HOUR = int(_getenv("RECAP_BEDTIME_UTC_START_HOUR", "12"))
RECAP_MORNING_LOOKBACK_HOURS = float(_getenv("RECAP_MORNING_LOOKBACK_HOURS", "10.0"))
RECAP_MARKET_TIMEZONE = _getenv("RECAP_MARKET_TIMEZONE", "America/New_York")
RECAP_MARKET_OPEN_TIME = _getenv("RECAP_MARKET_OPEN_TIME", "09:30")
RECAP_OPENING_LOOKBACK_MINUTES = int(_getenv("RECAP_OPENING_LOOKBACK_MINUTES", "10"))
RECAP_OPENING_RUN_AFTER_MINUTES = int(_getenv("RECAP_OPENING_RUN_AFTER_MINUTES", "8"))
RECAP_OPENING_RUN_GRACE_MINUTES = int(_getenv("RECAP_OPENING_RUN_GRACE_MINUTES", "20"))
SHADOW_AI_DECISION_ENABLED = _getenv_bool("SHADOW_AI_DECISION_ENABLED", "true")
SHADOW_AI_DECISION_LOOKBACK_DAYS = int(_getenv("SHADOW_AI_DECISION_LOOKBACK_DAYS", "3"))
SHADOW_AI_DECISION_DAY1_MAX_RANK = int(_getenv("SHADOW_AI_DECISION_DAY1_MAX_RANK", "5"))
SHADOW_AI_DECISION_OLDER_MAX_RANK = int(_getenv("SHADOW_AI_DECISION_OLDER_MAX_RANK", "1"))
SHADOW_AI_DECISION_BASE_BONUS = float(_getenv("SHADOW_AI_DECISION_BASE_BONUS", "18.0"))
SHADOW_AI_DECISION_DECAY_PER_DAY = float(_getenv("SHADOW_AI_DECISION_DECAY_PER_DAY", "6.0"))
SHADOW_AI_DECISION_RANK_DECAY = float(_getenv("SHADOW_AI_DECISION_RANK_DECAY", "1.5"))

# ============ Scanner Profile（條件組）===========
SCANNER_PROFILE = os.getenv("SCANNER_PROFILE", "balanced").lower()  # balanced | monster_v1

# monster_v1（偏妖股掃描）
SCANNER_MONSTER_PRICE_MIN = float(os.getenv("SCANNER_MONSTER_PRICE_MIN", "2.0"))
SCANNER_MONSTER_PRICE_MAX = float(os.getenv("SCANNER_MONSTER_PRICE_MAX", "20.0"))
SCANNER_MONSTER_MCAP_MAX = float(os.getenv("SCANNER_MONSTER_MCAP_MAX", "2000000000"))
SCANNER_MONSTER_RELVOL_MIN = float(os.getenv("SCANNER_MONSTER_RELVOL_MIN", "3.0"))
SCANNER_MONSTER_DAY_CHANGE_MIN = float(os.getenv("SCANNER_MONSTER_DAY_CHANGE_MIN", "5.0"))
SCANNER_MONSTER_DOLLAR_VOL_M_MIN = float(os.getenv("SCANNER_MONSTER_DOLLAR_VOL_M_MIN", "10.0"))
SCANNER_MONSTER_FLOAT_TIGHTNESS_MIN = float(os.getenv("SCANNER_MONSTER_FLOAT_TIGHTNESS_MIN", "6.0"))
SCANNER_MONSTER_FLOAT_ROTATION_MIN = float(os.getenv("SCANNER_MONSTER_FLOAT_ROTATION_MIN", "0.03"))
SCANNER_MONSTER_KEEP_MIN_SCORE = float(os.getenv("SCANNER_MONSTER_KEEP_MIN_SCORE", "34.0"))
SCANNER_MONSTER_WATCH_MIN_SCORE = float(os.getenv("SCANNER_MONSTER_WATCH_MIN_SCORE", "22.0"))

# ============ A/B/C 評級設定 ============
# A 級條件
GRADE_A_UPSIDE = 30.0          # 上漲空間 >30%
GRADE_A_ANALYSTS = 15          # 分析師數 >15
GRADE_A_SECTORS = ['Technology', 'Healthcare', 'Utilities', 'Industrials']

# B 級條件
GRADE_B_UPSIDE = 15.0          # 上漲空間 >15%
GRADE_B_7D_GAIN = 8.0          # 7日漲幅 >8%

# ============ 通知設定（選用）============
NOTIFICATION_ENABLED = False
NOTIFICATION_EMAIL = "your-email@gmail.com"
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
DISCORD_WEBHOOK_URL = _getenv("DISCORD_WEBHOOK_URL", "")

# ============ Turso 雲端最新狀態同步（選用）============
TURSO_ENABLED = _getenv_bool("TURSO_ENABLED", "false")
TURSO_DATABASE_URL = _getenv("TURSO_DATABASE_URL", "")
TURSO_AUTH_TOKEN = _getenv("TURSO_AUTH_TOKEN", "")
TURSO_CONNECT_RETRY_COUNT = int(_getenv("TURSO_CONNECT_RETRY_COUNT", "1"))
TURSO_CONNECT_RETRY_DELAY_SEC = float(_getenv("TURSO_CONNECT_RETRY_DELAY_SEC", "1.0"))

# ============ TradingView Webhook 訊號設定 ============
USE_TRADINGVIEW_SIGNALS = True
TV_WEBHOOK_SECRET = _getenv("TV_WEBHOOK_SECRET", "")
TV_WEBHOOK_PASSPHRASE = _getenv("TV_WEBHOOK_PASSPHRASE", TV_WEBHOOK_SECRET)
SIGNAL_STORE_PATH = _getenv("SIGNAL_STORE_PATH", "signals.db")
SIGNAL_MAX_AGE_MINUTES = int(_getenv("SIGNAL_MAX_AGE_MINUTES", "240"))
SIGNAL_REQUIRE_SAME_DAY = _getenv("SIGNAL_REQUIRE_SAME_DAY", "true").lower() == "true"
SIGNAL_STORE_RETENTION_DAYS = int(_getenv("SIGNAL_STORE_RETENTION_DAYS", "4"))
SIGNAL_RAW_LOG_RETENTION_DAYS = int(_getenv("SIGNAL_RAW_LOG_RETENTION_DAYS", "4"))
ALLOW_PLAIN_TEXT_WEBHOOK = _getenv_bool("ALLOW_PLAIN_TEXT_WEBHOOK", "false")
WEBHOOK_HOST = _getenv("WEBHOOK_HOST", "0.0.0.0")
WEBHOOK_PORT = int(_getenv("WEBHOOK_PORT", "8000"))
TV_AUTO_EXECUTION_ALERTS_ENABLED = _getenv_bool("TV_AUTO_EXECUTION_ALERTS_ENABLED", "true")
TV_EXECUTION_ALERTS_TOP_N = int(_getenv("TV_EXECUTION_ALERTS_TOP_N", "5"))

# ============ Repo 內建盤中 execution engine ============
INTRADAY_ENGINE_ENABLED = _getenv_bool("INTRADAY_ENGINE_ENABLED", "true")
INTRADAY_DATA_PROVIDER = _getenv("INTRADAY_DATA_PROVIDER", "auto").lower()  # auto | finnhub | yfinance
INTRADAY_INTERVAL = _getenv("INTRADAY_INTERVAL", "5m")
INTRADAY_PERIOD = _getenv("INTRADAY_PERIOD", "5d")
INTRADAY_PREPOST = _getenv_bool("INTRADAY_PREPOST", "false")
INTRADAY_FINNHUB_TIMEOUT_SEC = float(_getenv("INTRADAY_FINNHUB_TIMEOUT_SEC", "10.0"))
INTRADAY_ACTIVE_START_LOCAL = _getenv("INTRADAY_ACTIVE_START_LOCAL", "21:20")
INTRADAY_ACTIVE_END_LOCAL = _getenv("INTRADAY_ACTIVE_END_LOCAL", "05:10")
INTRADAY_ACTIVE_TIMEZONE = _getenv("INTRADAY_ACTIVE_TIMEZONE", "Asia/Taipei")
INTRADAY_TOP_N = int(_getenv("INTRADAY_TOP_N", "5"))
INTRADAY_MAX_SYMBOLS = int(_getenv("INTRADAY_MAX_SYMBOLS", "8"))
INTRADAY_POLL_SECONDS = int(_getenv("INTRADAY_POLL_SECONDS", "300"))
INTRADAY_IDLE_POLL_SECONDS = int(_getenv("INTRADAY_IDLE_POLL_SECONDS", "900"))
INTRADAY_HEARTBEAT_ENABLED = _getenv_bool("INTRADAY_HEARTBEAT_ENABLED", "true")
INTRADAY_HEARTBEAT_INTERVAL_MINUTES = int(_getenv("INTRADAY_HEARTBEAT_INTERVAL_MINUTES", "30"))
INTRADAY_STOP_LOSS_PCT = float(_getenv("INTRADAY_STOP_LOSS_PCT", "-3.0"))
INTRADAY_TAKE_PROFIT_PCT = float(_getenv("INTRADAY_TAKE_PROFIT_PCT", "6.0"))
INTRADAY_MIN_ADD_PROFIT_PCT = float(_getenv("INTRADAY_MIN_ADD_PROFIT_PCT", "1.5"))
INTRADAY_MAX_ADD_COUNT = int(_getenv("INTRADAY_MAX_ADD_COUNT", "2"))
INTRADAY_ENTRY_SIZE_FRACTION = float(_getenv("INTRADAY_ENTRY_SIZE_FRACTION", "0.33"))
INTRADAY_ADD_SIZE_FRACTION = float(_getenv("INTRADAY_ADD_SIZE_FRACTION", "0.25"))
INTRADAY_REDUCE_SIZE_FRACTION = float(_getenv("INTRADAY_REDUCE_SIZE_FRACTION", "0.5"))

# ============ Discord Bot（回報成交 / 查詢部位）============
DISCORD_BOT_ENABLED = _getenv_bool("DISCORD_BOT_ENABLED", "false")
DISCORD_BOT_TOKEN = _getenv("DISCORD_BOT_TOKEN", "")
DISCORD_BOT_PREFIX = _getenv("DISCORD_BOT_PREFIX", "!")
DISCORD_BOT_ALLOWED_CHANNEL_IDS = _getenv("DISCORD_BOT_ALLOWED_CHANNEL_IDS", "")
DISCORD_BOT_SYNC_GUILD_ID = _getenv("DISCORD_BOT_SYNC_GUILD_ID", "")

# ============ Demo / TV 補圖清單設定 ============
DEMO_MODE = os.getenv("DEMO_MODE", "false").lower() == "true"
TV_LIST_LIMIT = int(os.getenv("TV_LIST_LIMIT", "6"))